<?php
    include('include/header.php');
?>
    <div>
        <article>
            <section>
                <p>RESTAURENTE</p>
            </section>
            <aside>
            </aside>
        </article>
    </div>
<?php
    include('include/footer.php');
?>  
</body>
</html>